# Copyright 2020 IBM Corporation All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0

dist: xenial
language: python
python: 3.7.2

install:
  - pip install -r requirements.txt

script:
  - make lint
  - make beautify
  # If there are any code differences after beautifying exit with an error code
  - git diff --exit-code
